// filename : cmd.h

//----------------------------------------------------
// コマンドリスト
//----------------------------------------------------
const char* COMMAND_TBL[] = {
  "_START_!",
  "SYS/VERSION!",
  "SYS/SET_LOG:0!",
  "SYS/SET_LOG:1!",
  "SYS/BOOT!",
  "========================",
  "DIGITAL/OUTPUT:17:1!",
  "DIGITAL/OUTPUT:17:0!",
  "- - - - - - - - - - - - ",
  "DIGITAL/INPUT:18!",
  "DIGITAL/INPUT:14!",
  "DIGITAL/INPUT:13!",
  "========================",
  "ANALOG/SETUP:2:4!",
  "ANALOG/INPUT!",
  "- - - - - - - - - - - - ",
  "ANALOG/READ:0:0!",
  "ANALOG/READ:0:1!",
  "ANALOG/READ:0:2!",
  "ANALOG/READ:0:3!",
  "- - - - - - - - - - - - ",
  "ANALOG/READ:1:0!",
  "ANALOG/READ:1:1!",
  "ANALOG/READ:1:2!",
  "ANALOG/READ:1:3!",
  "========================",
  "PWM/OUTPUT:0:100!",
  "PWM/OUTPUT:0:600!",
  "PWM/INFO/CONNECT!",
  "========================",
  "MP3/TRACK/PLAY:1:1:101!",
  "MP3/TRACK/PLAY:1:2:1!",
  "MP3/TRACK/PLAY:1:3:1!",
  "MP3/TRACK/PLAY:1:4:1!",
  "MP3/TRACK/PLAY:1:2:101!",
  "- - - - - - - - - - - - ",
  "MP3/TRACK/STOP:1!",
  "MP3/TRACK/PAUSE:1!",
  "MP3/TRACK/START:1!",
  "MP3/TRACK/LOOP:1:0!",
  "MP3/TRACK/LOOP:1:1!",
  "- - - - - - - - - - - - ",
  "MP3/SET/VOLUME:1:5!",
  "MP3/SET/VOLUME:1:10!",
  "MP3/SET/VOLUME:1:20!",
  "MP3/SET/VOLUME:1:30!",
  "- - - - - - - - - - - - ",
  "MP3/SET/EQ:1:0!",
  "MP3/SET/EQ:1:1!",
  "MP3/SET/EQ:1:2!",
  "MP3/SET/EQ:1:3!",
  "MP3/SET/EQ:1:4!",
  "MP3/SET/EQ:1:5!",
  "- - - - - - - - - - - - ",
  "MP3/INFO/TRACK:1!" ,
  "MP3/INFO/VOLUME:1!",
  "MP3/INFO/EQ:1!"    ,
  "MP3/INFO/FILEID:1!",
  "MP3/INFO/FILES:1!" ,
  "MP3/INFO/CONNECT:1!",
  "MP3/INFO/CONNECT:2!",
};
const int TOTAL_CMDs = sizeof(COMMAND_TBL) / sizeof(COMMAND_TBL[0]);