RMDIR /s /q  .\build\
RMDIR /s /q  .\__pycache__\
RMDIR /s /q  .\main\__pycache__\
RMDIR /s /q  .\main\データセット\__pycache__\
RMDIR /s /q  .\main\コントローラ\更新\__pycache__\
RMDIR /s /q  .\main\コントローラ\更新\P移動\__pycache__\
RMDIR /s /q  .\main\コントローラ\更新\P衝突\__pycache__\
RMDIR /s /q  .\main\コントローラ\更新\P発射\__pycache__\
RMDIR /s /q  .\main\コントローラ\更新\P出現\__pycache__\
RMDIR /s /q  .\main\コントローラ\描画\__pycache__\
RMDIR /s /q  .\main\オブジェクト\キャラ\__pycache__\
RMDIR /s /q  .\main\オブジェクト\キャラ\自機\__pycache__\
RMDIR /s /q  .\main\オブジェクト\キャラ\敵機\__pycache__\
RMDIR /s /q  .\main\オブジェクト\キャラ\弾\__pycache__\
RMDIR /s /q  .\main\オブジェクト\演出\爆発\__pycache__\
RMDIR /s /q  .\main\オブジェクト\演出\背景\__pycache__\
RMDIR /s /q  .\main\オブジェクト\シーン\__pycache__\
RMDIR /s /q  .\main\オブジェクト\シーン\プレイ画面\__pycache__\
RMDIR /s /q  .\main\オブジェクト\シーン\タイトル画面\__pycache__\
RMDIR /s /q  .\main\オブジェクト\シーン\終了画面\__pycache__\
RMDIR /s /q  .\main\オブジェクト\管理\特殊効果\__pycache__\
RMDIR /s /q  .\main\汎用部品\__pycache__\